cache:
  directories:
  - "$HOME/.cache/pip"
  - "$HOME/.pyenv"

matrix:
  include:
  - os: linux
    python: '2.7'
  - os: linux
    python: '3.6'
  - os: osx
    language: objective-c
    env: PYENV_VERSION=2.7.12
  - os: osx
    language: objective-c
    env: PYENV_VERSION=3.5.2
# command to install dependencies
before_install:
  - source .travis/before_install.sh
install:
  - source .travis/install.sh
# command to run tests
script:
  - source .travis/run.sh
